### ISSUE TITLE
218: ohjelma antoi liitteenä olevan virheilmoituksen (broadcast_socket_connect_failure)

### ISSUE THREAD

**Issue by n4sjamk-docker** [N4SJAMK/teamboard-feedback#113]
Hei, ohjelma antoi liitteenä olevan virheilmoituksen (broadcast_socket_connect_failure). Ei siis näyttänyt tauluja, eikä antanut tehdä uusia..

**Comment by narsuman** [comment]
Kiitoksia palautteesta!

Palvelun on taas käytössä!
