### ISSUE TITLE
42: Ticket activation if other covering it

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#21]
Ticket activation if other covering it
1. You want ot activate/check a ticket which is covered by couple other tickets
2. You click selected ticket to see what is the topic of ticket
3. Edit mode will be activated activated!

Possible flow:
1. Ticket is moved on the top of pile and edit mode is not activated
2. If you you want to edit you will click again same ticket

**Comment by narsuman** [comment]
Will be obsolote after new client implementation

Will be closed now.
