### ISSUE TITLE
44: Backgroud change is not working correctly

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#23]
Backgroud change is not working correctly?

I have been testing teamboard.n4sjamk.org version today 12.9.2014

I noticed when I tried to change background it wont change after selection?

**Comment by narsuman** [comment]
I was not invited on the board which background I was changing. There should be a indicator/dialog tom inform user eg. "You don't have permission to do changes. Request invitation....."

**Comment by narsuman** [comment]
closed now
