### ISSUE TITLE
48: If you write a topic with scandic you will see some problems..

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#26]
Problems with scandinavian keys..
If you write a topic with scandic you will see some problems...

Eg. Määrittelytehtävä 1

It will be shown on your own screen correctly, but another client will see MÄ¤.Ä¤rittelytehtÄ¤vÄ¤

This is a duplicate bug...

**Comment by narsuman** [comment]
Still problems with new client ?

**Comment by narsuman** [comment]
This issue was moved to N4SJAMK/teamboard-client-react#14
