### ISSUE TITLE
47: If you have activated "fullscreen" -mode and you have a ticket with topic written using Scandinavian alphabets eg

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#27]
If you have activated "fullscreen" -mode and you have a ticket with topic written using Scandinavian alphabets eg. "Tämä on otsikko" it will be shown during move "TÄ¤mÄ¤ on otsikko" ?

Move is done by another client. After.

**Comment by narsuman** [comment]
Closed 

obsolete now.
