### ISSUE TITLE
54: Tein tiketin iPadillani => klikkasin Save => tiketti hävisi bittiavaruuteen

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#32]

**Comment by HelSu** [comment]
Could this be that the client has accidentally pushed next to save button? Could we fix this by: making bigger save button? or adding the ticket anyway if client pushes outside the ticket? I think the bigger problem is that the client loses the ticket than client has to delete ticket afterwards.

**Comment by narsuman** [comment]
Will be obsolote after new client implementation

Will be closed now.
