### ISSUE TITLE
57: Sovellus antaa kirjoittaa uden nimen lankulle, mutta muutos ei tallennu jos lankkuun ei ole oikeuksia

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#34]
Sovellus antaa kirjoittaa uden nimen lankulle, mutta muutos ei tallenn jos lankkuun ei ole oikeuksia

**Comment by HelSu** [comment]
Screenshot included. Check uservoice for more information.

**Comment by narsuman** [comment]
Will be obsolete after new client implementation

Will be closed now.
