### ISSUE TITLE
59: I added the workflow-image, but it didn't came

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#37]

**Comment by HelSu** [comment]
I added the workflow-image, but it didn't came. Only minimap shows new workflow-image. This is a private board, i'm not the author but i am invited.

**Comment by HelSu** [comment]
Screenshot included. go to uservoice to see it.

**Comment by narsuman** [comment]
Working ok! Verified 18.11.2014
