### ISSUE TITLE
68: Jos menen guest userilla ja laitan preview-näkymän päälle

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#43]

**Comment by HelSu** [comment]
Jos menen guest userilla ja laitan preview-näkymän päälle, se vaatii sulkiessa näkymän superuser tunnuksia ja logaa ulos guestistä!

**Comment by narsuman** [comment]
Will be obsolote after new client implementation

Will be closed now.
