### ISSUE TITLE
70: When I'm at create ticket-view

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#47]
attachments: []
body: When I'm at create ticket-view, i cannot give feedback (or include screenshot), because feedback button is behind the dark area. This should definitely be fixed.
channel: ttcon
created_at: 2014/10/28 10:46:30 +0000
id: 49493866
is_admin_response: False
plaintext_body: When I'm at create ticket-view, i cannot give feedback (or include screenshot), because feedback button is behind the dark area. This should definitely be fixed.
sender: {u'name': u'hel.sutinen', u'title': None, u'url': u'http://n4sjamk.uservoice.com/users/57294806-hel-sutinen', u'created_at': u'2014/09/25 09:42:22 +0000', u'updated_at': u'2014/09/29 11:15:39 +0000', u'id': 57294806, u'avatar_url': u'https://secure.gravatar.com/avatar/c8fd00075d0b99d1d8478c47b48142ec?size=70&default=https://assets0.uvcdn.com/pkg/admin/icons/user_70-c68d06098b40646a91b7656094632c19.png', u'karma_score': 0, u'email': u'hel.sutinen@gmail.com'}
updated_at: 2014/10/28 10:46:30 +0000

**Comment by narsuman** [comment]
closed now
