### ISSUE TITLE
69: There was no alert when trying to sign in without registering.

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#48]
attachments: []
body: There was no alert when trying to sign in without registering.
channel: ttcon
created_at: 2014/10/28 08:29:36 +0000
id: 49484374
is_admin_response: False
plaintext_body: There was no alert when trying to sign in without registering.
sender: {u'name': u'hel.sutinen', u'title': None, u'url': u'http://n4sjamk.uservoice.com/users/57294806-hel-sutinen', u'created_at': u'2014/09/25 09:42:22 +0000', u'updated_at': u'2014/09/29 11:15:39 +0000', u'id': 57294806, u'avatar_url': u'https://secure.gravatar.com/avatar/c8fd00075d0b99d1d8478c47b48142ec?size=70&default=https://assets0.uvcdn.com/pkg/admin/icons/user_70-c68d06098b40646a91b7656094632c19.png', u'karma_score': 0, u'email': u'hel.sutinen@gmail.com'}
updated_at: 2014/10/28 08:29:36 +0000

**Comment by narsuman** [comment]
Closed obsolote now..
