### ISSUE TITLE
81: If I try to join as Guest on the board using JAMK Windows desktop (Chrome ) 38.0.2125.111

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#57]
If I try to join as Guest on the board  using JAMK Windows desktop (Chrome )  38.0.2125.111. I wont be able to get in. 

If I try Incoginto mode I can  access board?

**Comment by narsuman** [comment]
This issue was moved to N4SJAMK/teamboard-client#6
