### ISSUE TITLE
83: Long description will be jammeing UI

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#59]
Long description will be jammeing UI 

If I create very long description on ticket it will be jammed for a several second > 15 second..

I tried to paste  message  "öäöäöäöäöäöäöäöäööääöäöä" X 50 times and duriing paste UI will be jammed..

**Comment by narsuman** [comment]
This issue was moved to N4SJAMK/teamboard-client#5
