### ISSUE TITLE
87: I tried to register with my iPad

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#63]
I tried to register with my iPad. When I clicked he Register button, I got an error message: insertDocument :: caused by :: 11000 E11000 duplicate key error index: development.users.$email_1 dup key: { : "huojo.jamk@gmail.com" }

**Comment by tanelih** [comment]
Should be fixed in the latest version of API.

**Comment by narsuman** [comment]
Will be obsolote after new client implementation

Will be closed now.
