### ISSUE TITLE
90: Boardin valinta kääntyy päin vastaiseksi jos painaa takaisin nappia kun board on valittuna ja palautuu jos tekee uudestaan.

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-feedback#66]
Boardin valinta kääntyy päin vastaiseksi jos painaa takaisin nappia kun board on valittuna ja palautuu jos tekee uudestaan.

**Comment by narsuman** [comment]
Will be obsolote after new client implementation

Will be closed now.
