### ISSUE TITLE
Long board names overflow

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-feedback#76]
![image](https://cloud.githubusercontent.com/assets/8721037/6729377/7c267512-ce3a-11e4-9faf-9875fc1f2bbf.png)

**Comment by narsuman** [comment]
This issue was moved to N4SJAMK/teamboard-client-react#4

**Comment by narsuman** [comment]
This issue was moved to N4SJAMK/teamboard-client-react#5
