### ISSUE TITLE
Long ticket content overflows ticket boarders

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-feedback#78]
![image](https://cloud.githubusercontent.com/assets/8721037/6729407/b3918c80-ce3a-11e4-8183-fcef6301f27e.png)
![image](https://cloud.githubusercontent.com/assets/8721037/6729652/500e7d3c-ce3d-11e4-9261-b5b4a98b858b.png)

**Comment by narsuman** [comment]
This issue was moved to N4SJAMK/teamboard-client-react#10
