### ISSUE TITLE
Add board failure

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-feedback#82]
Sometimes creating a board logs you out. After logging in there is a error message stuck on screen.

![image](https://cloud.githubusercontent.com/assets/8721037/6729758/4ad2c912-ce3e-11e4-93cd-a7011e7e267b.png)

![image](https://cloud.githubusercontent.com/assets/8721037/6729763/5ba95dfa-ce3e-11e4-8fea-95a9624c0121.png)

**Comment by narsuman** [comment]
This issue was moved to N4SJAMK/teamboard-client-react#6
