### ISSUE TITLE
153: Android-puhelimella tulee Error - saisiko puhelimille jonkin ilmoituksen Lankun/Contriboardin toimivuudesta eri alustoilla

### ISSUE THREAD

**Issue by n4sjamk-docker** [N4SJAMK/teamboard-feedback#87]
Android-puhelimella tulee Error - saisiko puhelimille jonkin ilmoituksen Lankun/Contriboardin toimivuudesta eri alustoilla?

**Comment by narsuman** [comment]
This issue was moved to N4SJAMK/teamboard-img#4
