### ISSUE TITLE
175: Workshopissa kokeillaan ja tuli vastaan ongelma

### ISSUE THREAD

**Issue by n4sjamk-docker** [N4SJAMK/teamboard-feedback#93]
Moro

Workshopissa kokeillaan ja tuli vastaan ongelma.  Jos lapun kirjoittaminen kestää yli 10s joku timeout hävittää lapun ja sinne jo kirjoitetun.

Kikka-3 on kirjoittaa notepadiin ja sitten copy-paste. Onko muita kikkoja?

Ps. Selain of firefox

**Comment by narsuman** [comment]
This issue was moved to N4SJAMK/teamboard-client-react#20
